### PR TITLE
Support for Elasticsearch plugins

### PR DESCRIPTION
**Pull request by petericebear**
This Pull Requests is for adding plugin support to Elasticsearch integration.

### CODE REVIEW

**Comment by petericebear** [comment]
The changes are mostly creating a local /es/plugins folder and set the right permissions of 1000:1000 as the owner for it.

Installing plugins through the action can de done with:
```
      - name: Start Elasticsearch
        uses: ./elasticsearch
        with:
          stack-version: 7.15.1
          plugins: |
            ingest-attachment
            analysis-icu
```

By installing it to a local folder it can be mounted to the number of nodes starting up onwards. 
There is a check if the plugins parameters is being used by the script.

**Comment by petericebear** [comment]
The action failing is odd, I did not make any changes for it. The other ones failed earlier since docker.elastic.co had some timeouts. Let me know what you think of this addition.

**Review by delvedor — APPROVED** [review]

**Review by picandocodigo — APPROVED** [review]
Thank you @petericebear!

**Comment by petericebear** [comment]
> Thank you @petericebear!

Awesome, when it is merged I will testdrive it further in the demo enviroment.

**Pull request merged**
